
language: python
python: 3.5
sudo: required
dist: trusty

os:
  - linux
  - osx

matrix:

  exclude:
    - python: 3.5

  include:
    - os: linux
      python: 2.7

    - os: linux
      python: 3.3

    - os: linux
      python: 3.4

    - os: linux
      python: 3.5
      env:
        - DEPLOY_DOC="yes"
        - RUN_COVERAGE="yes"

    - os: linux
      python: nightly

#    - os: linux
#      python: pypy
#
#    - os: linux
#      python: pypy3

    - os: osx
      language: objective-c
      python: 2.7
      env:
        - PY=2
        - PY_SUFFIX=

    - os: osx
      language: objective-c
      python: 3.5
      env:
        - PY=3
        - PY_SUFFIX=3

before_install:
  - cat /etc/hosts
  - sudo hostname "$(hostname | cut -c1-63)"
  - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts > /tmp/hosts
  - sudo mv /tmp/hosts /etc/hosts
  - cat /etc/hosts

  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$PY" == "3" ]]; then brew install python$PY_SUFFIX; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python$PY_SUFFIX; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install python$( python -c 'import sys; print("%d.%d" % sys.version_info[:2])' )-dev || true    ; fi

  - pip install -U pip setuptools wheel
  - pip install -r requirement.txt

install:
  - pip install -ve .

script:
  - if [[ "RUN_COVERAGE" == "yes" ]];
      then coverage run --source khayyam $(which nosetests);
      else nosetests;
    fi

after_success:
  - if [[ "RUN_COVERAGE" == "yes" ]]; then coveralls ; fi

deploy:
  provider: pypi
  user: Vahid.Mardani
  password:
    secure: "R1///eV2H4wsIpXDkTeMJFdFyipLc+vMDVF/wSs6L0Z0TSQOlspsxCayagpIDIUuiXm4hgx5u3UmLlA/7YjSkabdiYGZqgKs8EiksQtSxiAF5qQRI90IWDbZOR6pujIZ44Y/cMZdxvXUUQ533PW4hHixqCwkrTE5971K11mmzGM="

  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    all_branches: true
    distributions: sdist bdist_wheel
    repo: pylover/khayyam
    condition: "$TRAVIS_TAG =~ ^v[0-9][.][0-9]*[.][0-9]*$"


#before_deploy:
#  - "echo 'ready?'"

after_deploy:
  - if [[ "DEPLOY_DOC" == "yes" ]]; then ./travis-gh-pages.sh ; fi
