
language: python

#env:
#  - PYTHON=python PYSUF='' PYVER=2.7 PIPVER=''
#  - PYTHON=python3 PYSUF='3' PYVER=3.2 PIPVER='==7.1.2'

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "pypy"

before_install:
  - sudo apt-get update
  - sudo apt-get install python$( python -c 'import sys; print("%d.%d" % sys.version_info[:2])' )-dev || true
  - pip install cython
  - pip install coverage
  - pip install coveralls
  - pip install rtl

install:
  - pip install -e .

script:
  coverage run setup.py test

after_success:
  coveralls